"""Create a demo experiment with synthetic videos so every feature can be tried without a camera."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from . import synthetic as syn
from . import templates
from .project import Behaviour, Group, Project


def create_demo_project(path: str | Path, n_per_group: int = 3, seconds: float = 30.0, fps: float = 25.0,
                        track: bool = True, progress=None) -> Project:
    """Open-field demo: "Control" animals explore the centre more than "Anxious" animals."""
    path = Path(path)
    proj = Project(name="Demo open field", description="Synthetic open-field experiment generated by mANY-MAZE.",
                   protocol="open_field", test_duration_s=seconds)
    proj.path = path
    path.mkdir(parents=True, exist_ok=True)
    vids = path / "videos"
    vids.mkdir(exist_ok=True)
    app = templates.build("open_field", 50, 50, 300, 300, size_cm=40)
    app.frame_size = (400, 400)
    proj.apparatus.append(app)
    proj.groups = [Group("Control", "#3b82f6"), Group("Anxious", "#ef4444")]
    proj.behaviours = [Behaviour("Rearing", "r", "state"), Behaviour("Grooming", "g", "state"),
                       Behaviour("Defecation", "d", "point")]
    proj.stages = ["Day 1"]
    proj.analysis.bin_length_s = 10.0
    n = int(seconds * fps)
    k = 0
    total = 2 * n_per_group
    for gi, group in enumerate(["Control", "Anxious"]):
        for i in range(n_per_group):
            aid = f"{'C' if gi == 0 else 'A'}{i + 1}"
            proj.ensure_animal(aid, group)
            seed = 10 * gi + i
            if group == "Control":
                pos = syn.random_walk(n, (50, 50, 350, 350), speed=3.2, seed=seed, pause_prob=0.004)
            else:
                # anxious animals hug the walls: random walk confined to a ring near the wall
                pos = _wall_walk(n, (50, 50, 350, 350), seed=seed)
            vp = vids / f"{aid}.avi"
            syn.make_video(vp, pos, size=(400, 400), fps=fps, arena=("rect", 50, 50, 300, 300), seed=seed)
            t = proj.add_test(str(vp), aid, app.name, stage="Day 1", trial=1)
            t.events = [{"behaviour": "Rearing", "t": 3.0 + i, "t_end": 5.0 + i},
                        {"behaviour": "Defecation", "t": 12.0 + 2 * gi, "t_end": None}]
            k += 1
            if progress:
                progress(0.5 * k / total)
    proj.save()
    if track:
        for j, t in enumerate(proj.tests):
            proj.track_test(t)
            if progress:
                progress(0.5 + 0.5 * (j + 1) / len(proj.tests))
        proj.save()
    return proj


def _wall_walk(n, bounds, seed=0, speed=3.0):
    rng = np.random.default_rng(seed)
    x0, y0, x1, y1 = bounds
    m = 32
    # perimeter loop with noise and pauses
    per = [(x0 + m, y0 + m), (x1 - m, y0 + m), (x1 - m, y1 - m), (x0 + m, y1 - m)]
    pts = []
    pauses = {}
    for lap in range(20):
        for j, p in enumerate(per):
            q = (p[0] + rng.normal(0, 6), p[1] + rng.normal(0, 6))
            pts.append(q)
            if rng.random() < 0.3:
                pauses[len(pts) - 1] = int(rng.integers(30, 90))
    path = syn.waypoint_path(pts, speed_px_per_frame=speed, pauses=pauses)
    start = int(rng.integers(0, 50))
    return path[start:start + n]
